spring:
  application:
    name: business
  profiles:
    active: test


security:
  oauth2:
    resource:
      userInfoUri: http://localhost/authorization/user
      #filter-order: 0
      #preferTokenInfo: false

#management.security.enabled: false