server:
  port: 8888

spring:
  application:
    name: config
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/configs
        git:
          uri: http://....git
  profiles:
    active: native

